---
- name: Check for replay (/opt/gfs_create_done exists)
  stat:
    path: /opt/gfs_create_done
  register: gfs_create_done

- name: property set stonith-enabled
  shell: "pcs property set stonith-enabled=false"
  register: task_result
  until: task_result.rc == 0
  retries: 25
  delay: 10
  ignore_errors: yes

- name: property set no-quorum-policy
  shell: "pcs property set no-quorum-policy=freeze"
  register: task_result
  until: task_result.rc == 0
  retries: 25
  delay: 10
  ignore_errors: yes

- name: Create resource dlm
  shell: "pcs resource create dlm systemd:dlm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true"
  register: task_result
  until: task_result.rc == 0
  retries: 25
  delay: 10
  ignore_errors: yes

- name: Create resource clvmd
  shell: "pcs resource create clvmd ocf:heartbeat:clvm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true"
  register: task_result
  until: task_result.rc == 0
  retries: 25
  delay: 10
  ignore_errors: yes

- name: Create constraint order start
  shell: "pcs constraint order start dlm-clone then clvmd-clone"
  register: task_result
  until: task_result.rc == 0
  retries: 25
  delay: 10
  ignore_errors: yes

- name: pvcreate
  shell: "pvcreate /dev/sda"
  register: task_result
  until: task_result.rc == 0
  retries: 25
  delay: 10
  ignore_errors: yes

- name: Create cluster_vg
  shell: "vgcreate -Ay -cy cluster_vg /dev/sda"
  register: task_result
  until: task_result.rc == 0
  retries: 25
  delay: 10
  ignore_errors: yes

- name: Create cluster_lv
  shell: "lvcreate -L900M -n cluster_lv cluster_vg"
  register: task_result
  until: task_result.rc == 0
  retries: 25
  delay: 10
  ignore_errors: yes

- name: Create GFS2
  shell: "mkfs.gfs2 -O -j3 -p lock_dlm -t otusha:gfs2 /dev/cluster_vg/cluster_lv"
  register: task_result
  until: task_result.rc == 0
  retries: 25
  delay: 10
  ignore_errors: yes

- name: Create resource clusterfs
  shell: 'pcs resource create clusterfs Filesystem device="/dev/cluster_vg/cluster_lv" directory="/mnt/gfs2"  fstype="gfs2" "options=noatime" op monitor interval=10s  on-fail=ignore clone interleave=true'
  register: task_result
  until: task_result.rc == 0
  retries: 25
  delay: 10
  ignore_errors: yes

- name: Create constraint order
  shell: "pcs constraint order start clvmd-clone then clusterfs-clone"
  register: task_result
  until: task_result.rc == 0
  retries: 25
  delay: 10
  ignore_errors: yes

- name: Create constraint colocation
  shell: "pcs constraint colocation add clusterfs-clone with clvmd-clone"
  register: task_result
  until: task_result.rc == 0
  retries: 25
  delay: 10
  ignore_errors: yes

  when:
    - gfs_create_done.stat.exists != True

- name: Set replay protection (/opt/gfs_create_done)
  file:
    path: /opt/gfs_create_done
    state: touch
    owner: root
    group: root
    mode: '0744'
  when:
    - gfs_create_done.stat.exists != True
